name: 'Copy environment variable to file'
description: 'Copy environment variable to file'
inputs:
  content:  # env var or secret
    description: 'The content to write to the file'
    required: true
  filename:  # filename
    description: 'Where to write the file'
    required: true
  work-directory:
    description: 'Directory where to write the file'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
